Updated Cloud File Browser to loop correctly
DivvyHQ/cloud-file-browser-nodejs pull request #2
Opened 2018-05-17 15:27 UTC by mccarrion

This PR updated the loop that will run validateToken in order for it to loop over each service now. It also sets a delay for initElement, so that the firstElement does not initialize before validateToken is run.

2018-05-17 19:04 UTC, asermax-machinalis requested changes
Functionality wise this seems like it will work, but the code itself is not very realible.

2018-05-17 19:04 UTC, asermax-machinalis commented on divvy/cloudfilebrowser.js
> +            setTimeout(function(){cloudFileBrowser.initElement(firstElement);}, 1000);
If you're doing this timeout to manage the async behavior of the validate token before trying to init the services, it's not very safe. You're asuming the token validation will take at most 1000ms, which may be true for the test you're doing but it can change depending on the network and availability of the service. If this is the case, try using promises or some other reliable mechanism to deal with the asynchronous behavior of this code (let me know if you need help with these).

2018-05-17 19:14 UTC, nmallare commented on divvy/cloudfilebrowser.js
> +            setTimeout(function(){cloudFileBrowser.initElement(firstElement);}, 1000);
@asermax-machinalis I'll work with him, if I have time. Do you recommend just reading the jQuery docs for examples or do you have something else you recommend?

2018-05-17 19:24 UTC, asermax-machinalis commented on divvy/cloudfilebrowser.js
> +            setTimeout(function(){cloudFileBrowser.initElement(firstElement);}, 1000);
This library doesn't depend on jQuery, but our app has it available so it should be safe to use it. I think the easiest would be to use jQuery indeed, wrapping the callbacks using  [Deferreds](http://api.jquery.com/jQuery.Deferred/) to wrap the callbacks and maybe using [`jQuery.when`](http://api.jquery.com/jQuery.when/) for grouping them together.

2018-05-18 16:15 UTC, mccarrion commented
@asermax-machinalis I have pushed the updated code that we worked on together. Code has been tested and verified to work correctly. Please review and let me know your thoughts.

2018-05-18 17:33 UTC, asermax-machinalis approved these changes

2018-05-18 19:26 UTC, merged